/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from '.././orval-mutator';




export const handleStripeWebhook = (
    handleStripeWebhookBody: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/webhooks/stripe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: handleStripeWebhookBody, signal
    },
      );
    }
  


export const getHandleStripeWebhookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleStripeWebhook>>, TError,{data: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof handleStripeWebhook>>, TError,{data: string}, TContext> => {

const mutationKey = ['handleStripeWebhook'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleStripeWebhook>>, {data: string}> = (props) => {
          const {data} = props ?? {};

          return  handleStripeWebhook(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type HandleStripeWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof handleStripeWebhook>>>
    export type HandleStripeWebhookMutationBody = string
    export type HandleStripeWebhookMutationError = unknown

    export const useHandleStripeWebhook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleStripeWebhook>>, TError,{data: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof handleStripeWebhook>>,
        TError,
        {data: string},
        TContext
      > => {

      const mutationOptions = getHandleStripeWebhookMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    