/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CityNameRequest,
  CityNameResponse,
  CityResponse,
  CreateCityRequest,
  CreatePlaceRequest,
  PlaceResponse,
  UpdateCityRequest,
  UpdatePlaceRequest
} from '.././model';

import { customInstance } from '.././orval-mutator';




export const getCity = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityResponse>(
      {url: `/api/admin/cities/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCityQueryKey = (id?: number,) => {
    return [
    `/api/admin/cities/${id}`
    ] as const;
    }

    
export const getGetCityQueryOptions = <TData = Awaited<ReturnType<typeof getCity>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCityQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCity>>> = ({ signal }) => getCity(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCityQueryResult = NonNullable<Awaited<ReturnType<typeof getCity>>>
export type GetCityQueryError = unknown


export function useGetCity<TData = Awaited<ReturnType<typeof getCity>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCity>>,
          TError,
          Awaited<ReturnType<typeof getCity>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCity<TData = Awaited<ReturnType<typeof getCity>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCity>>,
          TError,
          Awaited<ReturnType<typeof getCity>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCity<TData = Awaited<ReturnType<typeof getCity>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetCity<TData = Awaited<ReturnType<typeof getCity>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCityQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateCity = (
    id: number,
    updateCityRequest: UpdateCityRequest,
 ) => {
      
      
      return customInstance<CityResponse>(
      {url: `/api/admin/cities/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCityRequest
    },
      );
    }
  


export const getUpdateCityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCity>>, TError,{id: number;data: UpdateCityRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCity>>, TError,{id: number;data: UpdateCityRequest}, TContext> => {

const mutationKey = ['updateCity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCity>>, {id: number;data: UpdateCityRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCity(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCityMutationResult = NonNullable<Awaited<ReturnType<typeof updateCity>>>
    export type UpdateCityMutationBody = UpdateCityRequest
    export type UpdateCityMutationError = unknown

    export const useUpdateCity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCity>>, TError,{id: number;data: UpdateCityRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCity>>,
        TError,
        {id: number;data: UpdateCityRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteCity = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/cities/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCity>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCity>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCity>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCity(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCity>>>
    
    export type DeleteCityMutationError = unknown

    export const useDeleteCity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCity>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCity>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateCityName = (
    cityId: number,
    nameId: number,
    cityNameRequest: CityNameRequest,
 ) => {
      
      
      return customInstance<CityNameResponse>(
      {url: `/api/admin/cities/${cityId}/names/${nameId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: cityNameRequest
    },
      );
    }
  


export const getUpdateCityNameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCityName>>, TError,{cityId: number;nameId: number;data: CityNameRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCityName>>, TError,{cityId: number;nameId: number;data: CityNameRequest}, TContext> => {

const mutationKey = ['updateCityName'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCityName>>, {cityId: number;nameId: number;data: CityNameRequest}> = (props) => {
          const {cityId,nameId,data} = props ?? {};

          return  updateCityName(cityId,nameId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCityNameMutationResult = NonNullable<Awaited<ReturnType<typeof updateCityName>>>
    export type UpdateCityNameMutationBody = CityNameRequest
    export type UpdateCityNameMutationError = unknown

    export const useUpdateCityName = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCityName>>, TError,{cityId: number;nameId: number;data: CityNameRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCityName>>,
        TError,
        {cityId: number;nameId: number;data: CityNameRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCityNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteCityName = (
    cityId: number,
    nameId: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/cities/${cityId}/names/${nameId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCityNameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCityName>>, TError,{cityId: number;nameId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCityName>>, TError,{cityId: number;nameId: number}, TContext> => {

const mutationKey = ['deleteCityName'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCityName>>, {cityId: number;nameId: number}> = (props) => {
          const {cityId,nameId} = props ?? {};

          return  deleteCityName(cityId,nameId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCityNameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCityName>>>
    
    export type DeleteCityNameMutationError = unknown

    export const useDeleteCityName = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCityName>>, TError,{cityId: number;nameId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCityName>>,
        TError,
        {cityId: number;nameId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCityNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPlace = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse>(
      {url: `/api/admin/cities/places/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPlaceQueryKey = (id?: number,) => {
    return [
    `/api/admin/cities/places/${id}`
    ] as const;
    }

    
export const getGetPlaceQueryOptions = <TData = Awaited<ReturnType<typeof getPlace>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlaceQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlace>>> = ({ signal }) => getPlace(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPlaceQueryResult = NonNullable<Awaited<ReturnType<typeof getPlace>>>
export type GetPlaceQueryError = unknown


export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPlace<TData = Awaited<ReturnType<typeof getPlace>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPlaceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updatePlace = (
    id: number,
    updatePlaceRequest: UpdatePlaceRequest,
 ) => {
      
      
      return customInstance<PlaceResponse>(
      {url: `/api/admin/cities/places/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePlaceRequest
    },
      );
    }
  


export const getUpdatePlaceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: number;data: UpdatePlaceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: number;data: UpdatePlaceRequest}, TContext> => {

const mutationKey = ['updatePlace'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlace>>, {id: number;data: UpdatePlaceRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePlace(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlace>>>
    export type UpdatePlaceMutationBody = UpdatePlaceRequest
    export type UpdatePlaceMutationError = unknown

    export const useUpdatePlace = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlace>>, TError,{id: number;data: UpdatePlaceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlace>>,
        TError,
        {id: number;data: UpdatePlaceRequest},
        TContext
      > => {

      const mutationOptions = getUpdatePlaceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deletePlace = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/cities/places/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeletePlaceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlace>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePlace>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePlace'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlace>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePlace(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlace>>>
    
    export type DeletePlaceMutationError = unknown

    export const useDeletePlace = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlace>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlace>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeletePlaceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listCities = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityResponse[]>(
      {url: `/api/admin/cities`, method: 'GET', signal
    },
      );
    }
  



export const getListCitiesQueryKey = () => {
    return [
    `/api/admin/cities`
    ] as const;
    }

    
export const getListCitiesQueryOptions = <TData = Awaited<ReturnType<typeof listCities>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCitiesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCities>>> = ({ signal }) => listCities(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCitiesQueryResult = NonNullable<Awaited<ReturnType<typeof listCities>>>
export type ListCitiesQueryError = unknown


export function useListCities<TData = Awaited<ReturnType<typeof listCities>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCities>>,
          TError,
          Awaited<ReturnType<typeof listCities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCities<TData = Awaited<ReturnType<typeof listCities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCities>>,
          TError,
          Awaited<ReturnType<typeof listCities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCities<TData = Awaited<ReturnType<typeof listCities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListCities<TData = Awaited<ReturnType<typeof listCities>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListCitiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createCity = (
    createCityRequest: CreateCityRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityResponse>(
      {url: `/api/admin/cities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCityRequest, signal
    },
      );
    }
  


export const getCreateCityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCity>>, TError,{data: CreateCityRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCity>>, TError,{data: CreateCityRequest}, TContext> => {

const mutationKey = ['createCity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCity>>, {data: CreateCityRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCity(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCityMutationResult = NonNullable<Awaited<ReturnType<typeof createCity>>>
    export type CreateCityMutationBody = CreateCityRequest
    export type CreateCityMutationError = unknown

    export const useCreateCity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCity>>, TError,{data: CreateCityRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCity>>,
        TError,
        {data: CreateCityRequest},
        TContext
      > => {

      const mutationOptions = getCreateCityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listPlaces1 = (
    cityId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse[]>(
      {url: `/api/admin/cities/${cityId}/places`, method: 'GET', signal
    },
      );
    }
  



export const getListPlaces1QueryKey = (cityId?: number,) => {
    return [
    `/api/admin/cities/${cityId}/places`
    ] as const;
    }

    
export const getListPlaces1QueryOptions = <TData = Awaited<ReturnType<typeof listPlaces1>>, TError = unknown>(cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlaces1QueryKey(cityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlaces1>>> = ({ signal }) => listPlaces1(cityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(cityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListPlaces1QueryResult = NonNullable<Awaited<ReturnType<typeof listPlaces1>>>
export type ListPlaces1QueryError = unknown


export function useListPlaces1<TData = Awaited<ReturnType<typeof listPlaces1>>, TError = unknown>(
 cityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces1>>,
          TError,
          Awaited<ReturnType<typeof listPlaces1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPlaces1<TData = Awaited<ReturnType<typeof listPlaces1>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces1>>,
          TError,
          Awaited<ReturnType<typeof listPlaces1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPlaces1<TData = Awaited<ReturnType<typeof listPlaces1>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListPlaces1<TData = Awaited<ReturnType<typeof listPlaces1>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListPlaces1QueryOptions(cityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createPlace1 = (
    cityId: number,
    createPlaceRequest: CreatePlaceRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse>(
      {url: `/api/admin/cities/${cityId}/places`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlaceRequest, signal
    },
      );
    }
  


export const getCreatePlace1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace1>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlace1>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext> => {

const mutationKey = ['createPlace1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlace1>>, {cityId: number;data: CreatePlaceRequest}> = (props) => {
          const {cityId,data} = props ?? {};

          return  createPlace1(cityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlace1MutationResult = NonNullable<Awaited<ReturnType<typeof createPlace1>>>
    export type CreatePlace1MutationBody = CreatePlaceRequest
    export type CreatePlace1MutationError = unknown

    export const useCreatePlace1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace1>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlace1>>,
        TError,
        {cityId: number;data: CreatePlaceRequest},
        TContext
      > => {

      const mutationOptions = getCreatePlace1MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const addCityName = (
    cityId: number,
    cityNameRequest: CityNameRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityNameResponse>(
      {url: `/api/admin/cities/${cityId}/names`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cityNameRequest, signal
    },
      );
    }
  


export const getAddCityNameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCityName>>, TError,{cityId: number;data: CityNameRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addCityName>>, TError,{cityId: number;data: CityNameRequest}, TContext> => {

const mutationKey = ['addCityName'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCityName>>, {cityId: number;data: CityNameRequest}> = (props) => {
          const {cityId,data} = props ?? {};

          return  addCityName(cityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCityNameMutationResult = NonNullable<Awaited<ReturnType<typeof addCityName>>>
    export type AddCityNameMutationBody = CityNameRequest
    export type AddCityNameMutationError = unknown

    export const useAddCityName = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCityName>>, TError,{cityId: number;data: CityNameRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCityName>>,
        TError,
        {cityId: number;data: CityNameRequest},
        TContext
      > => {

      const mutationOptions = getAddCityNameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAllPlaces = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse[]>(
      {url: `/api/admin/cities/places`, method: 'GET', signal
    },
      );
    }
  



export const getListAllPlacesQueryKey = () => {
    return [
    `/api/admin/cities/places`
    ] as const;
    }

    
export const getListAllPlacesQueryOptions = <TData = Awaited<ReturnType<typeof listAllPlaces>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllPlacesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllPlaces>>> = ({ signal }) => listAllPlaces(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListAllPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof listAllPlaces>>>
export type ListAllPlacesQueryError = unknown


export function useListAllPlaces<TData = Awaited<ReturnType<typeof listAllPlaces>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllPlaces>>,
          TError,
          Awaited<ReturnType<typeof listAllPlaces>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAllPlaces<TData = Awaited<ReturnType<typeof listAllPlaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllPlaces>>,
          TError,
          Awaited<ReturnType<typeof listAllPlaces>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAllPlaces<TData = Awaited<ReturnType<typeof listAllPlaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListAllPlaces<TData = Awaited<ReturnType<typeof listAllPlaces>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllPlaces>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListAllPlacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




