/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddCompanyMemberRequest,
  AdminCompanyMemberResponse,
  AdminCompanyResponse,
  AdminGuideResponse,
  AdminRoleResponse,
  AdminUserResponse,
  AssignRoleRequest,
  CreateRoleRequest,
  UpdateCompanyRequest,
  UpdateUserRequest
} from '.././model';

import { customInstance } from '.././orval-mutator';




export const getUser = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminUserResponse>(
      {url: `/api/admin/users/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserQueryKey = (id?: number,) => {
    return [
    `/api/admin/users/${id}`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = unknown


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateUser = (
    id: number,
    updateUserRequest: UpdateUserRequest,
 ) => {
      
      
      return customInstance<AdminUserResponse>(
      {url: `/api/admin/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRequest
    },
      );
    }
  


export const getUpdateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserRequest}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: UpdateUserRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UpdateUserRequest
    export type UpdateUserMutationError = unknown

    export const useUpdateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: UpdateUserRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteUser = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/users/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = unknown

    export const useDeleteUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCompany = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCompanyResponse>(
      {url: `/api/admin/companies/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCompanyQueryKey = (id?: number,) => {
    return [
    `/api/admin/companies/${id}`
    ] as const;
    }

    
export const getGetCompanyQueryOptions = <TData = Awaited<ReturnType<typeof getCompany>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompany>>> = ({ signal }) => getCompany(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCompanyQueryResult = NonNullable<Awaited<ReturnType<typeof getCompany>>>
export type GetCompanyQueryError = unknown


export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompany>>,
          TError,
          Awaited<ReturnType<typeof getCompany>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompany>>,
          TError,
          Awaited<ReturnType<typeof getCompany>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetCompany<TData = Awaited<ReturnType<typeof getCompany>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompany>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCompanyQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const updateCompany = (
    id: number,
    updateCompanyRequest: UpdateCompanyRequest,
 ) => {
      
      
      return customInstance<AdminCompanyResponse>(
      {url: `/api/admin/companies/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCompanyRequest
    },
      );
    }
  


export const getUpdateCompanyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext> => {

const mutationKey = ['updateCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCompany>>, {id: number;data: UpdateCompanyRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCompany(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof updateCompany>>>
    export type UpdateCompanyMutationBody = UpdateCompanyRequest
    export type UpdateCompanyMutationError = unknown

    export const useUpdateCompany = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCompany>>, TError,{id: number;data: UpdateCompanyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCompany>>,
        TError,
        {id: number;data: UpdateCompanyRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCompanyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteCompany = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/companies/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteCompanyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCompany(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompany>>>
    
    export type DeleteCompanyMutationError = unknown

    export const useDeleteCompany = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompany>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCompanyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const assignRole = (
    id: number,
    assignRoleRequest: AssignRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminUserResponse>(
      {url: `/api/admin/users/${id}/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignRoleRequest, signal
    },
      );
    }
  


export const getAssignRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: number;data: AssignRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: number;data: AssignRoleRequest}, TContext> => {

const mutationKey = ['assignRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRole>>, {id: number;data: AssignRoleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  assignRole(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleMutationResult = NonNullable<Awaited<ReturnType<typeof assignRole>>>
    export type AssignRoleMutationBody = AssignRoleRequest
    export type AssignRoleMutationError = unknown

    export const useAssignRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: number;data: AssignRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignRole>>,
        TError,
        {id: number;data: AssignRoleRequest},
        TContext
      > => {

      const mutationOptions = getAssignRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listRoles = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminRoleResponse[]>(
      {url: `/api/admin/roles`, method: 'GET', signal
    },
      );
    }
  



export const getListRolesQueryKey = () => {
    return [
    `/api/admin/roles`
    ] as const;
    }

    
export const getListRolesQueryOptions = <TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRolesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoles>>> = ({ signal }) => listRoles(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListRolesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoles>>>
export type ListRolesQueryError = unknown


export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRoles>>,
          TError,
          Awaited<ReturnType<typeof listRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRoles>>,
          TError,
          Awaited<ReturnType<typeof listRoles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createRole = (
    createRoleRequest: CreateRoleRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminRoleResponse>(
      {url: `/api/admin/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRoleRequest, signal
    },
      );
    }
  


export const getCreateRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleRequest}, TContext> => {

const mutationKey = ['createRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRole>>, {data: CreateRoleRequest}> = (props) => {
          const {data} = props ?? {};

          return  createRole(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof createRole>>>
    export type CreateRoleMutationBody = CreateRoleRequest
    export type CreateRoleMutationError = unknown

    export const useCreateRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRole>>,
        TError,
        {data: CreateRoleRequest},
        TContext
      > => {

      const mutationOptions = getCreateRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listCompanyMembers = (
    companyId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCompanyMemberResponse[]>(
      {url: `/api/admin/companies/${companyId}/members`, method: 'GET', signal
    },
      );
    }
  



export const getListCompanyMembersQueryKey = (companyId?: number,) => {
    return [
    `/api/admin/companies/${companyId}/members`
    ] as const;
    }

    
export const getListCompanyMembersQueryOptions = <TData = Awaited<ReturnType<typeof listCompanyMembers>>, TError = unknown>(companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompanyMembersQueryKey(companyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompanyMembers>>> = ({ signal }) => listCompanyMembers(companyId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(companyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCompanyMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listCompanyMembers>>>
export type ListCompanyMembersQueryError = unknown


export function useListCompanyMembers<TData = Awaited<ReturnType<typeof listCompanyMembers>>, TError = unknown>(
 companyId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompanyMembers>>,
          TError,
          Awaited<ReturnType<typeof listCompanyMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCompanyMembers<TData = Awaited<ReturnType<typeof listCompanyMembers>>, TError = unknown>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompanyMembers>>,
          TError,
          Awaited<ReturnType<typeof listCompanyMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCompanyMembers<TData = Awaited<ReturnType<typeof listCompanyMembers>>, TError = unknown>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListCompanyMembers<TData = Awaited<ReturnType<typeof listCompanyMembers>>, TError = unknown>(
 companyId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanyMembers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListCompanyMembersQueryOptions(companyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const addCompanyMember = (
    companyId: number,
    addCompanyMemberRequest: AddCompanyMemberRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCompanyMemberResponse>(
      {url: `/api/admin/companies/${companyId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCompanyMemberRequest, signal
    },
      );
    }
  


export const getAddCompanyMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCompanyMember>>, TError,{companyId: number;data: AddCompanyMemberRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addCompanyMember>>, TError,{companyId: number;data: AddCompanyMemberRequest}, TContext> => {

const mutationKey = ['addCompanyMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCompanyMember>>, {companyId: number;data: AddCompanyMemberRequest}> = (props) => {
          const {companyId,data} = props ?? {};

          return  addCompanyMember(companyId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCompanyMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addCompanyMember>>>
    export type AddCompanyMemberMutationBody = AddCompanyMemberRequest
    export type AddCompanyMemberMutationError = unknown

    export const useAddCompanyMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCompanyMember>>, TError,{companyId: number;data: AddCompanyMemberRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCompanyMember>>,
        TError,
        {companyId: number;data: AddCompanyMemberRequest},
        TContext
      > => {

      const mutationOptions = getAddCompanyMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const toggleUserEnabled = (
    id: number,
 ) => {
      
      
      return customInstance<AdminUserResponse>(
      {url: `/api/admin/users/${id}/toggle-enabled`, method: 'PATCH'
    },
      );
    }
  


export const getToggleUserEnabledMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleUserEnabled>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleUserEnabled>>, TError,{id: number}, TContext> => {

const mutationKey = ['toggleUserEnabled'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleUserEnabled>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  toggleUserEnabled(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleUserEnabledMutationResult = NonNullable<Awaited<ReturnType<typeof toggleUserEnabled>>>
    
    export type ToggleUserEnabledMutationError = unknown

    export const useToggleUserEnabled = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleUserEnabled>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleUserEnabled>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getToggleUserEnabledMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const verifyGuide = (
    userId: number,
 ) => {
      
      
      return customInstance<AdminGuideResponse>(
      {url: `/api/admin/guides/${userId}/verify`, method: 'PATCH'
    },
      );
    }
  


export const getVerifyGuideMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyGuide>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyGuide>>, TError,{userId: number}, TContext> => {

const mutationKey = ['verifyGuide'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyGuide>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  verifyGuide(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyGuideMutationResult = NonNullable<Awaited<ReturnType<typeof verifyGuide>>>
    
    export type VerifyGuideMutationError = unknown

    export const useVerifyGuide = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyGuide>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyGuide>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getVerifyGuideMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const rejectGuide = (
    userId: number,
 ) => {
      
      
      return customInstance<AdminGuideResponse>(
      {url: `/api/admin/guides/${userId}/reject`, method: 'PATCH'
    },
      );
    }
  


export const getRejectGuideMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectGuide>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectGuide>>, TError,{userId: number}, TContext> => {

const mutationKey = ['rejectGuide'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectGuide>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  rejectGuide(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RejectGuideMutationResult = NonNullable<Awaited<ReturnType<typeof rejectGuide>>>
    
    export type RejectGuideMutationError = unknown

    export const useRejectGuide = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectGuide>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectGuide>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getRejectGuideMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const verifyCompany = (
    id: number,
 ) => {
      
      
      return customInstance<AdminCompanyResponse>(
      {url: `/api/admin/companies/${id}/verify`, method: 'PATCH'
    },
      );
    }
  


export const getVerifyCompanyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCompany>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['verifyCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  verifyCompany(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof verifyCompany>>>
    
    export type VerifyCompanyMutationError = unknown

    export const useVerifyCompany = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCompany>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyCompany>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getVerifyCompanyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const unverifyCompany = (
    id: number,
 ) => {
      
      
      return customInstance<AdminCompanyResponse>(
      {url: `/api/admin/companies/${id}/unverify`, method: 'PATCH'
    },
      );
    }
  


export const getUnverifyCompanyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unverifyCompany>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unverifyCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['unverifyCompany'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unverifyCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  unverifyCompany(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnverifyCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof unverifyCompany>>>
    
    export type UnverifyCompanyMutationError = unknown

    export const useUnverifyCompany = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unverifyCompany>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unverifyCompany>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getUnverifyCompanyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listUsers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminUserResponse[]>(
      {url: `/api/admin/users`, method: 'GET', signal
    },
      );
    }
  



export const getListUsersQueryKey = () => {
    return [
    `/api/admin/users`
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = unknown


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const listGuides = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminGuideResponse[]>(
      {url: `/api/admin/guides`, method: 'GET', signal
    },
      );
    }
  



export const getListGuidesQueryKey = () => {
    return [
    `/api/admin/guides`
    ] as const;
    }

    
export const getListGuidesQueryOptions = <TData = Awaited<ReturnType<typeof listGuides>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGuidesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGuides>>> = ({ signal }) => listGuides(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListGuidesQueryResult = NonNullable<Awaited<ReturnType<typeof listGuides>>>
export type ListGuidesQueryError = unknown


export function useListGuides<TData = Awaited<ReturnType<typeof listGuides>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGuides>>,
          TError,
          Awaited<ReturnType<typeof listGuides>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListGuides<TData = Awaited<ReturnType<typeof listGuides>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGuides>>,
          TError,
          Awaited<ReturnType<typeof listGuides>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListGuides<TData = Awaited<ReturnType<typeof listGuides>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListGuides<TData = Awaited<ReturnType<typeof listGuides>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGuides>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListGuidesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGuide = (
    userId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminGuideResponse>(
      {url: `/api/admin/guides/${userId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetGuideQueryKey = (userId?: number,) => {
    return [
    `/api/admin/guides/${userId}`
    ] as const;
    }

    
export const getGetGuideQueryOptions = <TData = Awaited<ReturnType<typeof getGuide>>, TError = unknown>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGuideQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGuide>>> = ({ signal }) => getGuide(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetGuideQueryResult = NonNullable<Awaited<ReturnType<typeof getGuide>>>
export type GetGuideQueryError = unknown


export function useGetGuide<TData = Awaited<ReturnType<typeof getGuide>>, TError = unknown>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuide>>,
          TError,
          Awaited<ReturnType<typeof getGuide>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGuide<TData = Awaited<ReturnType<typeof getGuide>>, TError = unknown>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGuide>>,
          TError,
          Awaited<ReturnType<typeof getGuide>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetGuide<TData = Awaited<ReturnType<typeof getGuide>>, TError = unknown>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetGuide<TData = Awaited<ReturnType<typeof getGuide>>, TError = unknown>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGuide>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetGuideQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteGuide = (
    userId: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/guides/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteGuideMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGuide>>, TError,{userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteGuide>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteGuide'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGuide>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteGuide(userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteGuideMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGuide>>>
    
    export type DeleteGuideMutationError = unknown

    export const useDeleteGuide = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGuide>>, TError,{userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGuide>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getDeleteGuideMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAllCompanyMembers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCompanyMemberResponse[]>(
      {url: `/api/admin/company-members`, method: 'GET', signal
    },
      );
    }
  



export const getListAllCompanyMembersQueryKey = () => {
    return [
    `/api/admin/company-members`
    ] as const;
    }

    
export const getListAllCompanyMembersQueryOptions = <TData = Awaited<ReturnType<typeof listAllCompanyMembers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAllCompanyMembersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllCompanyMembers>>> = ({ signal }) => listAllCompanyMembers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListAllCompanyMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listAllCompanyMembers>>>
export type ListAllCompanyMembersQueryError = unknown


export function useListAllCompanyMembers<TData = Awaited<ReturnType<typeof listAllCompanyMembers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompanyMembers>>,
          TError,
          Awaited<ReturnType<typeof listAllCompanyMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAllCompanyMembers<TData = Awaited<ReturnType<typeof listAllCompanyMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllCompanyMembers>>,
          TError,
          Awaited<ReturnType<typeof listAllCompanyMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListAllCompanyMembers<TData = Awaited<ReturnType<typeof listAllCompanyMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListAllCompanyMembers<TData = Awaited<ReturnType<typeof listAllCompanyMembers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllCompanyMembers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListAllCompanyMembersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const listCompanies = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<AdminCompanyResponse[]>(
      {url: `/api/admin/companies`, method: 'GET', signal
    },
      );
    }
  



export const getListCompaniesQueryKey = () => {
    return [
    `/api/admin/companies`
    ] as const;
    }

    
export const getListCompaniesQueryOptions = <TData = Awaited<ReturnType<typeof listCompanies>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCompaniesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCompanies>>> = ({ signal }) => listCompanies(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCompaniesQueryResult = NonNullable<Awaited<ReturnType<typeof listCompanies>>>
export type ListCompaniesQueryError = unknown


export function useListCompanies<TData = Awaited<ReturnType<typeof listCompanies>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompanies>>,
          TError,
          Awaited<ReturnType<typeof listCompanies>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCompanies<TData = Awaited<ReturnType<typeof listCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCompanies>>,
          TError,
          Awaited<ReturnType<typeof listCompanies>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCompanies<TData = Awaited<ReturnType<typeof listCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListCompanies<TData = Awaited<ReturnType<typeof listCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCompanies>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListCompaniesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const removeRole = (
    userId: number,
    roleName: string,
 ) => {
      
      
      return customInstance<AdminUserResponse>(
      {url: `/api/admin/users/${userId}/roles/${roleName}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRole>>, TError,{userId: number;roleName: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeRole>>, TError,{userId: number;roleName: string}, TContext> => {

const mutationKey = ['removeRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeRole>>, {userId: number;roleName: string}> = (props) => {
          const {userId,roleName} = props ?? {};

          return  removeRole(userId,roleName,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveRoleMutationResult = NonNullable<Awaited<ReturnType<typeof removeRole>>>
    
    export type RemoveRoleMutationError = unknown

    export const useRemoveRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRole>>, TError,{userId: number;roleName: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeRole>>,
        TError,
        {userId: number;roleName: string},
        TContext
      > => {

      const mutationOptions = getRemoveRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteRole = (
    id: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/roles/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRole>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteRole(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRoleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRole>>>
    
    export type DeleteRoleMutationError = unknown

    export const useDeleteRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRole>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const removeCompanyMember = (
    companyId: number,
    userId: number,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/admin/companies/${companyId}/members/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveCompanyMemberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeCompanyMember>>, TError,{companyId: number;userId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeCompanyMember>>, TError,{companyId: number;userId: number}, TContext> => {

const mutationKey = ['removeCompanyMember'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeCompanyMember>>, {companyId: number;userId: number}> = (props) => {
          const {companyId,userId} = props ?? {};

          return  removeCompanyMember(companyId,userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveCompanyMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeCompanyMember>>>
    
    export type RemoveCompanyMemberMutationError = unknown

    export const useRemoveCompanyMember = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeCompanyMember>>, TError,{companyId: number;userId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeCompanyMember>>,
        TError,
        {companyId: number;userId: number},
        TContext
      > => {

      const mutationOptions = getRemoveCompanyMemberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    