/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListToursParams,
  TourDetailResponse,
  TourSummaryResponse
} from '.././model';

import { customInstance } from '.././orval-mutator';




export const listTours = (
    params?: ListToursParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TourSummaryResponse[]>(
      {url: `/api/tours`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListToursQueryKey = (params?: ListToursParams,) => {
    return [
    `/api/tours`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListToursQueryOptions = <TData = Awaited<ReturnType<typeof listTours>>, TError = unknown>(params?: ListToursParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListToursQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTours>>> = ({ signal }) => listTours(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListToursQueryResult = NonNullable<Awaited<ReturnType<typeof listTours>>>
export type ListToursQueryError = unknown


export function useListTours<TData = Awaited<ReturnType<typeof listTours>>, TError = unknown>(
 params: undefined |  ListToursParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTours>>,
          TError,
          Awaited<ReturnType<typeof listTours>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListTours<TData = Awaited<ReturnType<typeof listTours>>, TError = unknown>(
 params?: ListToursParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTours>>,
          TError,
          Awaited<ReturnType<typeof listTours>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListTours<TData = Awaited<ReturnType<typeof listTours>>, TError = unknown>(
 params?: ListToursParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListTours<TData = Awaited<ReturnType<typeof listTours>>, TError = unknown>(
 params?: ListToursParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTours>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListToursQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getTourDetail = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<TourDetailResponse>(
      {url: `/api/tours/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTourDetailQueryKey = (id?: number,) => {
    return [
    `/api/tours/${id}`
    ] as const;
    }

    
export const getGetTourDetailQueryOptions = <TData = Awaited<ReturnType<typeof getTourDetail>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTourDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTourDetail>>> = ({ signal }) => getTourDetail(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTourDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getTourDetail>>>
export type GetTourDetailQueryError = unknown


export function useGetTourDetail<TData = Awaited<ReturnType<typeof getTourDetail>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTourDetail>>,
          TError,
          Awaited<ReturnType<typeof getTourDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTourDetail<TData = Awaited<ReturnType<typeof getTourDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTourDetail>>,
          TError,
          Awaited<ReturnType<typeof getTourDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTourDetail<TData = Awaited<ReturnType<typeof getTourDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetTourDetail<TData = Awaited<ReturnType<typeof getTourDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTourDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTourDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




