/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookingResponse,
  CreateCheckout200,
  CreateCheckoutBody,
  GetByCheckoutIdParams
} from '.././model';

import { customInstance } from '.././orval-mutator';




export const createCheckout = (
    createCheckoutBody: CreateCheckoutBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateCheckout200>(
      {url: `/api/bookings/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCheckoutBody, signal
    },
      );
    }
  


export const getCreateCheckoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckout>>, TError,{data: CreateCheckoutBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCheckout>>, TError,{data: CreateCheckoutBody}, TContext> => {

const mutationKey = ['createCheckout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckout>>, {data: CreateCheckoutBody}> = (props) => {
          const {data} = props ?? {};

          return  createCheckout(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckout>>>
    export type CreateCheckoutMutationBody = CreateCheckoutBody
    export type CreateCheckoutMutationError = unknown

    export const useCreateCheckout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckout>>, TError,{data: CreateCheckoutBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCheckout>>,
        TError,
        {data: CreateCheckoutBody},
        TContext
      > => {

      const mutationOptions = getCreateCheckoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getMyBookings = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<BookingResponse[]>(
      {url: `/api/bookings/mine`, method: 'GET', signal
    },
      );
    }
  



export const getGetMyBookingsQueryKey = () => {
    return [
    `/api/bookings/mine`
    ] as const;
    }

    
export const getGetMyBookingsQueryOptions = <TData = Awaited<ReturnType<typeof getMyBookings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyBookingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBookings>>> = ({ signal }) => getMyBookings(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMyBookingsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyBookings>>>
export type GetMyBookingsQueryError = unknown


export function useGetMyBookings<TData = Awaited<ReturnType<typeof getMyBookings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBookings>>,
          TError,
          Awaited<ReturnType<typeof getMyBookings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMyBookings<TData = Awaited<ReturnType<typeof getMyBookings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBookings>>,
          TError,
          Awaited<ReturnType<typeof getMyBookings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMyBookings<TData = Awaited<ReturnType<typeof getMyBookings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetMyBookings<TData = Awaited<ReturnType<typeof getMyBookings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBookings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMyBookingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getByCheckoutId = (
    params: GetByCheckoutIdParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BookingResponse>(
      {url: `/api/bookings/by-checkout`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetByCheckoutIdQueryKey = (params?: GetByCheckoutIdParams,) => {
    return [
    `/api/bookings/by-checkout`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetByCheckoutIdQueryOptions = <TData = Awaited<ReturnType<typeof getByCheckoutId>>, TError = unknown>(params: GetByCheckoutIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByCheckoutIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getByCheckoutId>>> = ({ signal }) => getByCheckoutId(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetByCheckoutIdQueryResult = NonNullable<Awaited<ReturnType<typeof getByCheckoutId>>>
export type GetByCheckoutIdQueryError = unknown


export function useGetByCheckoutId<TData = Awaited<ReturnType<typeof getByCheckoutId>>, TError = unknown>(
 params: GetByCheckoutIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByCheckoutId>>,
          TError,
          Awaited<ReturnType<typeof getByCheckoutId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetByCheckoutId<TData = Awaited<ReturnType<typeof getByCheckoutId>>, TError = unknown>(
 params: GetByCheckoutIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByCheckoutId>>,
          TError,
          Awaited<ReturnType<typeof getByCheckoutId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetByCheckoutId<TData = Awaited<ReturnType<typeof getByCheckoutId>>, TError = unknown>(
 params: GetByCheckoutIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetByCheckoutId<TData = Awaited<ReturnType<typeof getByCheckoutId>>, TError = unknown>(
 params: GetByCheckoutIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByCheckoutId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetByCheckoutIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




