/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CityResponse,
  CreatePlaceRequest,
  PlaceResponse
} from '.././model';

import { customInstance } from '.././orval-mutator';




export const listPlaces = (
    cityId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse[]>(
      {url: `/api/cities/${cityId}/places`, method: 'GET', signal
    },
      );
    }
  



export const getListPlacesQueryKey = (cityId?: number,) => {
    return [
    `/api/cities/${cityId}/places`
    ] as const;
    }

    
export const getListPlacesQueryOptions = <TData = Awaited<ReturnType<typeof listPlaces>>, TError = unknown>(cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlacesQueryKey(cityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlaces>>> = ({ signal }) => listPlaces(cityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(cityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof listPlaces>>>
export type ListPlacesQueryError = unknown


export function useListPlaces<TData = Awaited<ReturnType<typeof listPlaces>>, TError = unknown>(
 cityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces>>,
          TError,
          Awaited<ReturnType<typeof listPlaces>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPlaces<TData = Awaited<ReturnType<typeof listPlaces>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces>>,
          TError,
          Awaited<ReturnType<typeof listPlaces>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPlaces<TData = Awaited<ReturnType<typeof listPlaces>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListPlaces<TData = Awaited<ReturnType<typeof listPlaces>>, TError = unknown>(
 cityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListPlacesQueryOptions(cityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createPlace = (
    cityId: number,
    createPlaceRequest: CreatePlaceRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse>(
      {url: `/api/cities/${cityId}/places`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlaceRequest, signal
    },
      );
    }
  


export const getCreatePlaceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext> => {

const mutationKey = ['createPlace'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlace>>, {cityId: number;data: CreatePlaceRequest}> = (props) => {
          const {cityId,data} = props ?? {};

          return  createPlace(cityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof createPlace>>>
    export type CreatePlaceMutationBody = CreatePlaceRequest
    export type CreatePlaceMutationError = unknown

    export const useCreatePlace = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlace>>, TError,{cityId: number;data: CreatePlaceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlace>>,
        TError,
        {cityId: number;data: CreatePlaceRequest},
        TContext
      > => {

      const mutationOptions = getCreatePlaceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listCities1 = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityResponse[]>(
      {url: `/api/cities`, method: 'GET', signal
    },
      );
    }
  



export const getListCities1QueryKey = () => {
    return [
    `/api/cities`
    ] as const;
    }

    
export const getListCities1QueryOptions = <TData = Awaited<ReturnType<typeof listCities1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCities1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCities1>>> = ({ signal }) => listCities1(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListCities1QueryResult = NonNullable<Awaited<ReturnType<typeof listCities1>>>
export type ListCities1QueryError = unknown


export function useListCities1<TData = Awaited<ReturnType<typeof listCities1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCities1>>,
          TError,
          Awaited<ReturnType<typeof listCities1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCities1<TData = Awaited<ReturnType<typeof listCities1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listCities1>>,
          TError,
          Awaited<ReturnType<typeof listCities1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListCities1<TData = Awaited<ReturnType<typeof listCities1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useListCities1<TData = Awaited<ReturnType<typeof listCities1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCities1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListCities1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCity1 = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CityResponse>(
      {url: `/api/cities/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetCity1QueryKey = (id?: number,) => {
    return [
    `/api/cities/${id}`
    ] as const;
    }

    
export const getGetCity1QueryOptions = <TData = Awaited<ReturnType<typeof getCity1>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCity1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCity1>>> = ({ signal }) => getCity1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCity1QueryResult = NonNullable<Awaited<ReturnType<typeof getCity1>>>
export type GetCity1QueryError = unknown


export function useGetCity1<TData = Awaited<ReturnType<typeof getCity1>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCity1>>,
          TError,
          Awaited<ReturnType<typeof getCity1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCity1<TData = Awaited<ReturnType<typeof getCity1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCity1>>,
          TError,
          Awaited<ReturnType<typeof getCity1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCity1<TData = Awaited<ReturnType<typeof getCity1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetCity1<TData = Awaited<ReturnType<typeof getCity1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCity1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCity1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPlace1 = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PlaceResponse>(
      {url: `/api/cities/places/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPlace1QueryKey = (id?: number,) => {
    return [
    `/api/cities/places/${id}`
    ] as const;
    }

    
export const getGetPlace1QueryOptions = <TData = Awaited<ReturnType<typeof getPlace1>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlace1QueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlace1>>> = ({ signal }) => getPlace1(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPlace1QueryResult = NonNullable<Awaited<ReturnType<typeof getPlace1>>>
export type GetPlace1QueryError = unknown


export function useGetPlace1<TData = Awaited<ReturnType<typeof getPlace1>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace1>>,
          TError,
          Awaited<ReturnType<typeof getPlace1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPlace1<TData = Awaited<ReturnType<typeof getPlace1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace1>>,
          TError,
          Awaited<ReturnType<typeof getPlace1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPlace1<TData = Awaited<ReturnType<typeof getPlace1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetPlace1<TData = Awaited<ReturnType<typeof getPlace1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace1>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPlace1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




