/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface AdminCompanyMemberResponse {
  companyId?: number;
  companyName?: string;
  userId?: number;
  userFullName?: string;
  userEmail?: string;
  memberRole?: string;
  status?: string;
}
