/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface AdminGuideResponse {
  userId?: number;
  fullName?: string;
  email?: string;
  guideType?: string;
  verificationStatus?: string;
  bio?: string;
  languages?: string;
  companyId?: number;
  companyName?: string;
}
