/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface AiGenerateCircuitRequest {
  cityId: number;
  /**
   * @minimum 1
   * @maximum 7
   */
  numberOfDays: number;
  interests?: string[];
  travelDate?: string;
}
