/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface AiSuggestPlacesRequest {
  /**
   * @minimum 1
   * @maximum 10
   */
  count?: number;
  preferences?: string;
}
