/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface BookingResponse {
  id?: number;
  circuitSessionId?: number;
  circuitId?: number;
  tourName?: string;
  sessionStartDateTime?: string;
  amountMad?: number;
  status?: string;
  createdAt?: string;
  paidAt?: string;
}
