/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import type { CircuitStopResponse } from './circuitStopResponse';
import type { CircuitRouteResponse } from './circuitRouteResponse';

export interface CircuitResponse {
  id?: number;
  cityId?: number;
  cityName?: string;
  name?: string;
  notes?: string;
  createdAt?: string;
  createdBy?: number;
  stops?: CircuitStopResponse[];
  routes?: CircuitRouteResponse[];
}
