/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface CircuitStopResponse {
  id?: number;
  position?: number;
  dayNumber?: number;
  stopKind?: string;
  mealType?: string;
  startTime?: string;
  endTime?: string;
  durationMinutes?: number;
  notes?: string;
  placeId?: number;
  placeName?: string;
  placeCategory?: string;
  placeImage?: string;
  placeAddress?: string;
  placeLatitude?: number;
  placeLongitude?: number;
}
