/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface CircuitSummaryResponse {
  id?: number;
  cityId?: number;
  cityName?: string;
  name?: string;
  notes?: string;
  createdAt?: string;
  stopCount?: number;
}
