/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface CityNameResponse {
  id?: number;
  languageCode?: string;
  name?: string;
  primary?: boolean;
}
