/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface CreateCircuitRequest {
  cityId: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  name: string;
  notes?: string;
  /** @minimum 0 */
  priceMad?: number;
}
