/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface CreateCircuitSessionRequest {
  startDateTime: string;
  endDateTime?: string;
  /** @minimum 1 */
  maxParticipants?: number;
  notes?: string;
}
