/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface GuideBookingResponse {
  id?: number;
  circuitId?: number;
  circuitName?: string;
  circuitSessionId?: number;
  sessionStartDateTime?: string;
  sessionEndDateTime?: string;
  sessionStatus?: string;
  touristId?: number;
  touristName?: string;
  touristEmail?: string;
  touristPhone?: string;
  amountMad?: number;
  paymentStatus?: string;
  createdAt?: string;
  paidAt?: string;
}
