/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface GuideDashboardSummary {
  totalBookings?: number;
  confirmedBookings?: number;
  pendingBookings?: number;
  totalRevenue?: number;
  totalTourists?: number;
  totalCircuits?: number;
  upcomingSessions?: number;
}
