/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import type { RegisterRequestUserType } from './registerRequestUserType';

export interface RegisterRequest {
  userType: RegisterRequestUserType;
  /**
   * @minLength 0
   * @maxLength 150
   */
  fullName: string;
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  password: string;
  phone?: string;
  companyName?: string;
  companyDescription?: string;
  bio?: string;
  languages?: string;
}
