/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export type RegisterRequestUserType = typeof RegisterRequestUserType[keyof typeof RegisterRequestUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterRequestUserType = {
  TOURIST: 'TOURIST',
  COMPANY: 'COMPANY',
  GUIDE: 'GUIDE',
} as const;
