/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface TourSessionResponse {
  id?: number;
  startDateTime?: string;
  endDateTime?: string;
  maxParticipants?: number;
  bookedCount?: number;
  availablePlaces?: number;
  status?: string;
  userBooked?: boolean;
}
