/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */
import type { CircuitStopResponse } from './circuitStopResponse';
import type { TourSessionResponse } from './tourSessionResponse';

export interface TourDetailResponse {
  id?: number;
  name?: string;
  notes?: string;
  priceMad?: number;
  cityId?: number;
  cityName?: string;
  guideName?: string;
  stops?: CircuitStopResponse[];
  sessions?: TourSessionResponse[];
}
