/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface TourSummaryResponse {
  id?: number;
  name?: string;
  notes?: string;
  priceMad?: number;
  cityId?: number;
  cityName?: string;
  stopCount?: number;
  guideName?: string;
  nextSessionAt?: string;
  upcomingSessionCount?: number;
}
