/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface TransportOptionResponse {
  id?: number;
  fromPlaceId?: number;
  fromPlaceName?: string;
  toPlaceId?: number;
  toPlaceName?: string;
  mode?: string;
  name?: string;
  description?: string;
  bidirectional?: boolean;
  pricingType?: string;
  priceMad?: number;
  pricePerKmMad?: number;
  currency?: string;
  serviceStartTime?: string;
  serviceEndTime?: string;
  distanceKm?: number;
  durationMinutes?: number;
  createdAt?: string;
  createdBy?: number;
}
