/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface UpdateCompanyRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name?: string;
  description?: string;
}
