/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface UpdateTransportOptionRequest {
  /**
   * @minLength 0
   * @maxLength 30
   */
  mode?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  name?: string;
  description?: string;
  bidirectional?: boolean;
  /**
   * @minLength 0
   * @maxLength 20
   */
  pricingType?: string;
  priceMad?: number;
  pricePerKmMad?: number;
  /**
   * @minLength 0
   * @maxLength 3
   */
  currency?: string;
  serviceStartTime?: string;
  serviceEndTime?: string;
  distanceKm?: number;
  durationMinutes?: number;
}
