/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface UpdateUserRequest {
  /**
   * @minLength 1
   * @maxLength 150
   */
  fullName?: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 30
   */
  phone?: string;
  verified?: boolean;
}
