/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Tarikma API
 * Backend API for Tarik.ma
 * OpenAPI spec version: v1
 */

export interface UpsertCircuitRouteRequest {
  fromStopId: number;
  toStopId: number;
  /**
   * @minLength 0
   * @maxLength 30
   */
  transportMode?: string;
  transportOptionId?: number;
  distanceKm?: number;
  durationMinutes?: number;
}
